[package]
org = "thamindumiuranda"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerina"
name="test"
version="2201.10.4"
